-- ADICIONAR CAMPOS DE LOGIN AO CLIENTE (Fase 10)
ALTER TABLE customers ADD COLUMN IF NOT EXISTS email TEXT UNIQUE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS password TEXT;

-- GARANTIR COLUNAS DE LOG IN NA LOJA (Caso não existam)
ALTER TABLE stores ADD COLUMN IF NOT EXISTS admin_user TEXT DEFAULT 'admin';
ALTER TABLE stores ADD COLUMN IF NOT EXISTS admin_password TEXT DEFAULT 'vaptvupt123';

-- CRIAR ÍNDICE PARA BUSCA RÁPIDA DE PEDIDOS POR CLIENTE
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
